require("mvrcoag.plugins-setup")
require("mvrcoag.core.options")
require("mvrcoag.core.keymaps")
require("mvrcoag.core.colorscheme")
require("mvrcoag.plugins.comment")
require("mvrcoag.plugins.nvim-tree")
require("mvrcoag.plugins.lualine")
require("mvrcoag.plugins.telescope")
require("mvrcoag.plugins.nvim-cmp")
require("mvrcoag.plugins.lsp.mason")
require("mvrcoag.plugins.lsp.lspconfig")

